"""
RULE UPDATER — ARCHIVED 2026-07-17

This module has been retired. The rule_updater was an auto-tuning system
that proposed (and could auto-apply) signal weight changes based on performance
metrics. It was inert only because the paper engine's decisions database was empty.

Versions 5, 6, and 7 in the rule_versions table were auto-generated by this system.
It has been retired because a dormant capability with a live trigger condition
(an accidental database write away from auto-tuning) is a safety risk.

The concept is worth rebuilding deliberately:
- Wire to state.json's real outcome history
- Keep dry_run=True as a hard-coded default (not overridable in production)
- Route proposals to the user via Telegram for manual approval only
- Never auto-apply

Code preserved at ~/.trading/archive/rule_updater.py for reference.
"""

import logging

logger = logging.getLogger(__name__)


class RuleUpdater:
    """Archived stub — see ~/.trading/archive/rule_updater.py for original code."""

    def __init__(self, *args, **kwargs):
        raise RuntimeError(
            "RuleUpdater has been archived (2026-07-17). "
            "This auto-tuning system was retired because a dormant capability "
            "was one accidental database write away from live auto-application. "
            "See ~/.trading/archive/rule_updater.py for reference."
        )


def create_updater(*args, **kwargs):
    """Archived factory."""
    raise RuntimeError(
        "create_updater() has been archived (2026-07-17). "
        "See ~/.trading/archive/rule_updater.py for reference."
    )
