"""Execution Engine data models."""
from dataclasses import dataclass, field
from typing import Optional, Any


@dataclass
class OrderRequest:
    """Request to buy/sell a security."""
    symbol: str
    side: str  # BUY or SELL
    quantity: int  # shares for equities, units for forex
    order_type: str = "market"  # market | limit | stop
    price: Optional[float] = None  # None for market orders
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    reason: str = ""
    signal_ref: dict[str, Any] = field(default_factory=dict)
    strategy: str = ""  # which strategy generated this order


@dataclass
class OrderResult:
    """Result of a trade execution."""
    success: bool
    order_id: str  # UUID generated by the broker
    symbol: str
    side: str
    quantity: int
    price: float
    total: float  # quantity * price
    fee: float
    status: str  # filled | rejected | pending | cancelled
    message: str = ""
    timestamp: str = ""  # ISO format
    external_id: str = ""  # broker-specific order ID, empty for paper
    realised_pnl: Optional[float] = None  # populated on SELL


@dataclass
class SafetyVerdict:
    """Risk management decision on an order."""
    allowed: bool
    reason: str = ""
    violations: list[str] = field(default_factory=list)


@dataclass
class ExecutionReport:
    """Combined outcome of safety check + execution."""
    success: bool
    order: Optional[OrderResult] = None
    safety: Optional[SafetyVerdict] = None
    message: str = ""
    timestamp: str = ""  # ISO format


@dataclass
class AccountInfo:
    """Snapshot of trading account state."""
    cash: float
    equity: float  # cash + positions value
    buying_power: float
    positions_count: int
    daily_pnl: float
    daily_pnl_pct: float
    currency: str = "KES"
    broker: str = "paper"


@dataclass
class BrokerPosition:
    """Open position from a broker."""
    symbol: str
    quantity: int
    market_value: float
    cost_basis: float
    unrealized_pnl: float
    unrealized_pnl_pct: float