"""Data + signal layer for the LIVE-STRATEGY backtest.

Loads cached NSE daily bars (~2.5y) and reconstructs the SAME signals the
live allocation engine used, entirely offline (no network):

  * ranking score  -> trading.ranking.scorer.score_all_factors (pure math)
  * regime         -> trading.research.regimes.classify_regimes (pure math)

This mirrors the live system: the auto-trader's decisions come from
generate_rebalance_plan(prices=..., signals=..., portfolio=...), where
signals are ranking scores and the planner itself applies sector targets,
signal gates, daily-shift caps, stop-loss, and SUSPENDED_SYMBOLS exclusion.

We replay THAT engine — we do not reimplement the strategy.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

from trading import config
from trading.ranking import scorer
from trading.research import regimes

DATA_DIR = Path.home() / ".trading" / "data"
PORTFOLIO_DIR = Path.home() / ".trading" / "portfolio"

# Universe the live book actually traded (matches state.json + STRATEGY).
LIVE_UNIVERSE = ["ABSA", "COOP", "EABL", "SCOM", "KPLC", "KCB", "SCBK",
                 "BAMB", "TOTL", "KNRE", "EQTY", "WTK"]


def load_bars(symbol: str) -> Optional[pd.DataFrame]:
    """Load cached daily bars for one symbol. Returns df with cols
    [date, open, high, low, close, volume] indexed by date, or None."""
    p = DATA_DIR / f"nse_{symbol}.csv"
    if not p.exists():
        return None
    try:
        df = pd.read_csv(p)
    except Exception:
        return None
    df.columns = [c.strip().lower() for c in df.columns]
    if "date" not in df.columns or "close" not in df.columns:
        return None
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df = df.dropna(subset=["date"]).sort_values("date").reset_index(drop=True)
    for c in ("open", "high", "low", "close", "volume"):
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")
    return df


def load_all_bars(universe=LIVE_UNIVERSE) -> dict[str, pd.DataFrame]:
    out = {}
    for s in universe:
        df = load_bars(s)
        if df is not None and len(df) > 0:
            out[s] = df
    return out


def common_trading_dates(bars: dict[str, pd.DataFrame]) -> list[pd.Timestamp]:
    """Dates where ALL universe symbols have a close (traded day)."""
    sets = []
    for s, df in bars.items():
        sets.append(set(df["date"]))
    if not sets:
        return []
    common = set.intersection(*sets)
    return sorted(common)


def score_on_date(bars: dict[str, pd.DataFrame], date: pd.Timestamp) -> dict[str, float]:
    """Reconstruct ranking scores as-of `date` for every symbol with enough
    history. Uses scorer.score_all_factors over the trailing window up to date."""
    scores: dict[str, float] = {}
    # universe context for relative_strength needs all frames
    universe_frames = {}
    for s, df in bars.items():
        tail = df[df["date"] <= date]
        if len(tail) >= 260:  # scorer needs >=260 bars for regime factor
            universe_frames[s] = tail
    for s, df in bars.items():
        tail = df[df["date"] <= date]
        if len(tail) < 60:  # need some lookback for momentum/vol
            scores[s] = 50.0
            continue
        try:
            factors = scorer.score_all_factors(tail, universe=universe_frames)
            sc = scorer.aggregate_score(factors)
            scores[s] = float(sc)
        except Exception:
            scores[s] = 50.0
    return scores


def regime_on_date(bars: dict[str, pd.DataFrame], date: pd.Timestamp) -> str:
    """Market regime as-of date using a broad equity proxy (SCOM/EQTY/KCB)."""
    proxy = None
    for s in ("SCOM", "EQTY", "KCB"):
        if s in bars:
            tail = bars[s][bars[s]["date"] <= date]["close"].astype(float)
            if len(tail) >= 260:
                proxy = tail
                break
    if proxy is None:
        return "Sideways"
    try:
        trend, vol = regimes.classify_regimes(proxy)
        if len(trend) == 0:
            return "Sideways"
        t = trend.iloc[-1]
        return t  # "Bull" | "Bear" | "Sideways"
    except Exception:
        return "Sideways"


def load_initial_state() -> dict:
    """Replicate the live book's STARTING state (2026-07-13 13:52:30).

    The initial state.json was generated by PortfolioState.from_dict with
    cash=50% (seed behaviour), then the auto-trader's first run (14:01) did
    the 50k/50k split. We seed the backtest with the SAME post-first-run
    book so the replay starts from the real system, not an arbitrary one.
    """
    sp = PORTFOLIO_DIR / "state.json"
    if sp.exists():
        return json.loads(sp.read_text())
    # Fallback: 100k cash, no positions (should not happen in practice)
    return {
        "initial_capital": 100000.0,
        "cash": 100000.0,
        "positions": [],
        "max_drawdown_pct": 0.0,
    }
